[project]
name = "sync"
version = "0.4.2"
description = "Monorepo for developer automation: pr, rl, dp, glnt, cm"
authors = [
    {name = "antoniooreany"}
]
requires-python = ">=3.9"
dependencies = [
    "requests",
    "google-genai"
]

[project.scripts]
pr   = "pr_sync.cli:main"
rl   = "release_sync.cli:main"
dp   = "dependabot_sync.cli:main"
glnt = "gitlint_sync.cli:main"
cm   = "gitlint_sync.commit_generator:main"
gf   = "gitflow_sync.cli:main"
fs   = "feature_sync.cli:main"
vs   = "version_sync.cli:main"

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"



[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src"]
