import os
import subprocess
from pathlib import Path

def is_git_root() -> bool:
    """Check if the current working directory is a git repository root."""
    try:
        res_inside = subprocess.run(
            ["git", "rev-parse", "--is-inside-work-tree"],
            capture_output=True, text=True, check=True
        )
        if res_inside.stdout.strip() != "true":
            return False
            
        res_root = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True, text=True, check=True
        )
        toplevel = Path(res_root.stdout.strip()).resolve()
        cwd = Path.cwd().resolve()
        return toplevel == cwd
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False

def generate_gitlint_config() -> str:
    """Generate the standard .gitlint configuration string."""
    return """# Standard Gitlint configuration generated by gitlint-sync
[general]
ignore=title-trailing-punctuation, T3, body-is-missing
verbosity=2

[title-max-length]
line-length=72

[title-match-regex]
regex=^(feat|fix|docs|refactor|test|chore)(\\([\\w\\-]+\\))?!?: .*$
"""

def generate_commit_msg_hook() -> str:
    """Generate a cross-platform Python-based commit-msg hook script."""
    return """#!/usr/bin/env python
import sys
import subprocess

def main():
    commit_msg_filepath = sys.argv[1]
    try:
        res = subprocess.run(["gitlint", "--msg-filename", commit_msg_filepath])
        sys.exit(res.returncode)
    except FileNotFoundError:
        print("[gitlint] warning: gitlint executable not found. Skipping local commit message validation.", file=sys.stderr)
        sys.exit(0)

if __name__ == "__main__":
    main()
"""

def generate_workflow_config() -> str:
    """Generate the GitHub Actions commit-lint.yml workflow string."""
    return """name: commit-lint

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install gitlint
        run: pip install gitlint

      - name: Lint commits
        run: gitlint --commits origin/${{ github.event.pull_request.base.ref }}..HEAD
"""

def write_configs(target_dir: Path, force: bool = False) -> list[Path]:
    """Write all gitlint-related configuration files with safety checks."""
    git_dir = target_dir / ".git"
    if not git_dir.exists():
        raise FileNotFoundError("Not inside a git repository root (.git directory missing).")

    gitlint_file = target_dir / ".gitlint"
    hook_file = git_dir / "hooks" / "commit-msg"
    workflow_dir = target_dir / ".github" / "workflows"
    workflow_file = workflow_dir / "commit-lint.yml"

    # Check for existing files to enforce invariant
    existing = []
    if gitlint_file.exists():
        existing.append(str(gitlint_file.relative_to(target_dir)))
    if hook_file.exists():
        existing.append(".git/hooks/commit-msg")
    if workflow_file.exists():
        existing.append(".github/workflows/commit-lint.yml")

    if existing and not force:
        raise FileExistsError(f"Configuration files already exist: {', '.join(existing)}. Use --force to overwrite.")

    # Write .gitlint
    gitlint_file.write_text(generate_gitlint_config(), encoding="utf-8")

    # Write commit-msg hook
    hook_file.parent.mkdir(parents=True, exist_ok=True)
    hook_file.write_text(generate_commit_msg_hook(), encoding="utf-8")
    
    # Make hook executable on Unix systems
    if os.name != 'nt':
        try:
            hook_file.chmod(0o755)
        except Exception:
            pass

    # Write workflow
    workflow_dir.mkdir(parents=True, exist_ok=True)
    workflow_file.write_text(generate_workflow_config(), encoding="utf-8")

    return [gitlint_file, hook_file, workflow_file]
